from pathlib import Path
from html import escape
D=Path('dist')
sports=[('teams','Borough representative teams','Representing Hackney. Together.','Boys’ and girls’ district football, bringing together young players from primary schools across the borough.'),('cross-country','Cross country','Find your stride.','The Primary Cross Country League is part of HSAA’s planned 2026–27 sporting programme.'),('five-a-side','Five-a-side competition','Small teams. Big spirit.','School football competitions for boys and girls across Hackney.'),('nine-a-side','9-a-side','A new chapter for school football.','Boys’ and girls’ school leagues, bringing friendly rivalry back to the pitch.'),('kwik-cricket','Kwik cricket','Step up to the crease.','Kwik cricket is part of HSAA’s planned 2026–27 programme for Hackney primary schools.'),('tag-touch','Tag touch','Move together. Play together.','Tag rugby is part of HSAA’s planned 2026–27 sporting programme.'),('orienteering','Orienteering','Find your way, together.','Orienteering festivals are part of HSAA’s planned 2026–27 programme for Hackney primary schools.')]
children={'teams','five-a-side','nine-a-side','kwik-cricket'}
labels={s[0]:s[1] for s in sports}; labels.update({'home':'Home','contact':'Contact'})
def href(key):return key+'.html'
def navlink(key,label,current):return f'<a href="{href(key)}"'+(' aria-current="page"' if key==current else '')+f'>{label}</a>'
def shell(key,title,desc,body,parent=None):
 nav=''
 for slug,label,*_ in sports:
  if slug in children:
   nav+=f'<div class="nav-group">{navlink(slug,label,key)}<button class="submenu-toggle" aria-expanded="false" aria-controls="nav-{slug}" aria-label="Show {label} pages">⌄</button><div class="submenu" id="nav-{slug}">{navlink(slug+"-boys","Boys",key)}{navlink(slug+"-girls","Girls",key)}</div></div>'
  else:nav+=navlink(slug,label,key)
 footer=''.join(navlink(s,l,key) for s,l,*_ in sports)
 return f'''<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | HSAA</title><meta name="description" content="{escape(desc,quote=True)}"><link rel="icon" href="../assets/logo.jpg"><link rel="stylesheet" href="../css/styles.css"><script src="../js/main.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to content</a><header><div class="masthead wrap"><a href="home.html" class="brand" aria-label="HSAA home"><img src="../assets/logo.jpg" alt="Hackney Schools Athletic Association" width="215" height="64"></a><span class="brand-note">HACKNEY SCHOOLS<br><strong>ATHLETICS ASSOCIATION</strong></span><a class="header-contact" href="contact.html">Get in touch <span aria-hidden="true">↗</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu <span aria-hidden="true">☰</span></button></div><nav class="navigation" id="main-nav" aria-label="Main navigation"><div class="nav-inner wrap">{navlink('home','Home',key)}{nav}{navlink('contact','Contact',key)}</div></nav></header>
<main id="main">{body}</main><footer><div class="wrap footer-grid"><div><img src="../assets/logo.jpg" alt="HSAA" width="215" height="64" loading="lazy"><p>Sport. Opportunity. Community.<br>For the children of Hackney.</p><a href="mailto:info@hsaa.org.uk">info@hsaa.org.uk ↗</a></div><div><h2>Explore HSAA</h2><div class="footer-links">{navlink('home','Home',key)}{footer}{navlink('contact','Contact',key)}</div></div><div><h2>Boys &amp; girls</h2><div class="footer-links">{''.join(navlink(s+'-'+g,labels[s]+' — '+g,key) for s in ['teams','five-a-side','nine-a-side','kwik-cricket'] for g in ['boys','girls'])}</div></div></div><div class="wrap footer-bottom">© HSAA · Hackney Schools Athletics Association <a href="#main">Back to top ↑</a></div></footer></body></html>'''
def cards(items):return '<div class="sport-grid">'+''.join(f'<a class="sport-card" href="{s}.html"><span class="card-number">0{i+1} / {"FOOTBALL" if s in ["teams","five-a-side","nine-a-side"] else "SCHOOL SPORT"}</span><h3>{l}</h3><p>{d}</p><span class="card-arrow" aria-hidden="true">↗</span></a>' for i,(s,l,h,d) in enumerate(items))+'</div>'
def contactbox(subject='school sport'):return f'<aside class="enquiry"><span class="eyebrow">GET INVOLVED</span><h2>Bring your school<br>into the action.</h2><p>For {subject} enquiries, entry information and the latest arrangements, get in touch with HSAA.</p><a class="button" href="contact.html">Contact HSAA <span aria-hidden="true">↗</span></a></aside>'
def subnav(slug,current):return '<nav class="section-tabs" aria-label="Section navigation">'+''.join(navlink(k,l,current) for k,l in [(slug,'Overview'),(slug+'-boys','Boys'),(slug+'-girls','Girls')])+'</nav>'
def intro(key,title,heading,desc,parent=None):return f'<div class="wrap page-intro"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="home.html">Home</a><span>/</span>'+ (f'<a href="{parent}.html">{labels[parent]}</a><span>/</span>' if parent else '')+f'<span>{title}</span></nav><span class="eyebrow">HACKNEY SCHOOLS SPORT</span><h1>{heading}</h1><p class="lead">{desc}</p></div>'
home='''<div class="news-strip"><div class="wrap"><span class="eyebrow">FROM HSAA</span><p>Looking ahead to 2026–27 · School sport, new opportunities and a shared love of the game.</p><a href="contact.html">Enquiries ↗</a></div></div><section class="hero wrap"><div class="hero-copy"><span class="eyebrow">OUR SCHOOLS. OUR BOROUGH. OUR FUTURE.</span><h1>Every child.<br>Every chance.<br><em>Through sport.</em></h1><p>Welcome to Hackney Schools Athletics Association. Helping primary school children build confidence, find their team and discover a lifelong love of sport.</p><div class="actions"><a class="button" href="#sports">Explore our sports <span aria-hidden="true">↗</span></a><a class="text-link" href="teams.html">Meet our teams <span aria-hidden="true">→</span></a></div><div class="hero-footnote"><span class="small-mark" aria-hidden="true">✳</span> Rooted in Hackney. Open to possibility.</div></div><figure class="hero-photo"><img src="../assets/football-action.jpg" alt="Hackney girls playing football in front of the goal" width="1990" height="1508" fetchpriority="high"><figcaption><span>MORE THAN A GAME</span><strong>A place to belong.</strong></figcaption></figure></section><section class="values wrap" aria-label="Our values"><div><span>01</span><strong>Opportunity for every child</strong></div><div><span>02</span><strong>Teamwork that lasts</strong></div><div><span>03</span><strong>Proud to represent Hackney</strong></div></section><section class="section wrap" id="sports"><div class="section-heading"><div><span class="eyebrow">FIND YOUR GAME</span><h2>A borough full of possibility.</h2></div><p>From the football pitch to the cross-country course, discover sport for Hackney’s primary schools.</p></div>'''+cards(sports)+'''</section><section class="feature wrap"><img src="../assets/team-celebration.jpg" alt="Hackney players celebrating together with a trophy" width="884" height="1024" loading="lazy"><div><span class="eyebrow">ONE BOROUGH. A SHARED PRIDE.</span><h2>Local talent.<br>Lasting memories.</h2><p>Our boys’ and girls’ district teams give young footballers the opportunity to represent Hackney, meet players from other schools and compete beyond the borough.</p><p>The girls won the Southern Counties Cup in 2026, following the boys’ success in 2024.</p><a class="text-link" href="teams.html">Discover our representative teams →</a></div></section><section class="section wrap mission"><span class="eyebrow">WHY WE DO IT</span><h2>More than the final score.</h2><p>We believe sport is a powerful way to build teamwork, discipline and confidence. HSAA provides extra-curricular sporting opportunities and encourages healthy rivalry between schools and districts, underpinned by equal opportunities, child protection and safeguarding.</p><a class="text-link" href="contact.html">Be part of HSAA →</a></section>'''
(D/'html/home.html').write_text(shell('home','Home','School sport, competitions and borough representative teams for Hackney primary schools.',home),encoding='utf-8')
for slug,title,heading,desc in sports:
 body=intro(slug,title,heading,desc)
 if slug in children:body+='<div class="wrap">'+subnav(slug,slug)+'</div>'
 body+='<div class="wrap content-layout"><article class="article">'
 if slug=='teams':body+='''<img class="wide-image" src="../assets/girls-team.jpg" alt="Hackney girls district team, 2026"><h2>Proud to wear the Hackney shirt.</h2><p>HSAA oversees boys’ and girls’ district football teams for Hackney primary school children. Hackney is affiliated to Inner London County Schools FA and the English Schools’ FA.</p><p>The girls’ district team launched in the 2019–20 season. Both teams compete in district competitions and festivals, building experience and friendships through football.</p>'''
 elif slug=='nine-a-side':body+='''<img class="wide-image" src="../assets/schools-football.jpg" alt="Primary school footballers competing for the ball"><h2>The school league returns.</h2><p>School football has been organised by the association since 1891. In the 2025–26 academic year, the school league was re-established with twelve schools in each of the boys’ and girls’ leagues.</p><p>The leagues started at Mabley Green in November, with finals in May 2026. Contact HSAA for the next season’s arrangements.</p>'''
 elif slug=='five-a-side':body+='''<h2>School football, shared enthusiasm.</h2><p>Football is one of Hackney primary schools’ strongest sports for participation. HSAA supports locally organised competitions for boys and girls, working with partners to deliver an inclusive schools football calendar.</p><p>For five-a-side entry details, age groups, dates and venues, please contact HSAA.</p>'''
 else:body+=f'<h2>{title} for Hackney primary schools.</h2><p>{desc}</p><p>Schools must be affiliated to the Young &amp; Active 2030 Programme to take part in these planned sporting competitions.</p><h3>Taking part</h3><p>Contact HSAA for entry arrangements, eligible year groups, venues and event dates.</p>'
 if slug in children:body+='<div class="team-options">'+''.join(f'<a href="{slug}-{g}.html"><span>{g.title()}</span><strong>Explore {g}’ {"team" if slug=="teams" else "competition"} →</strong></a>' for g in ['boys','girls'])+'</div>'
 body+='</article>'+contactbox(title.lower())+'</div>'
 (D/f'html/{slug}.html').write_text(shell(slug,title,desc,body),encoding='utf-8')
 if slug not in children:continue
 for g in ['boys','girls']:
  key=slug+'-'+g; t=g.title()+'’ '+('borough representative team' if slug=='teams' else title.lower()); b=intro(key,t,t,desc,slug)+'<div class="wrap">'+subnav(slug,key)+'</div><div class="wrap content-layout"><article class="article">'
  if slug=='teams':
   b+=f'<figure><img class="wide-image" src="../assets/{g}-team.jpg" alt="Hackney {g} district team in 2026"><figcaption>Hackney {g} district team · 2026</figcaption></figure><h2>Representing our borough.</h2>'
   if g=='boys':b+='<p>The boys’ district team represents Hackney in schools football. Hackney has won the Inner London Kay Trophy eight times, most recently in 2024–25, and the Lester Finch Trophy five times.</p><p>The team also won the Southern Counties Cup in 1984 and 2024. Many boys who have represented the district have gone on to receive county honours.</p>'
   else:b+='<p>Launched in 2019–20, the girls’ district team became Inner London County Schools FA Girls Counties District Champions in 2022–23 and 2025–26, and won the Girls Southern Counties Cup for the first time in 2026.</p><h3>Competitions and festivals</h3><ul><li>ESFA National Cup</li><li>London Girls District League</li><li>John Larter Girls District Trophy</li><li>Kent County Schools FA Girls U11 District Cup</li><li>Girls Southern Counties Cup</li></ul><p>The team also takes part in the Swansea Schools’ FA Festival for Girls, finishing as runners-up in 2022–23.</p>'
   b+='<h3>Joining the team</h3><p>Schools and families can contact HSAA for information about selection and opportunities to represent Hackney.</p><h3>Safeguarding</h3><p>District coaches with both teams hold updated FA DBS certificates and have completed the necessary FA child safeguarding training.</p>'
  elif slug=='nine-a-side':
   b+=f'<h2>{g.title()}’ school league</h2><p>The {g}’ league was re-established in 2025–26, with twelve schools participating. Games began at Mabley Green in November and the finals took place in May 2026.</p><p>Contact HSAA for fixtures, league information and entry arrangements for the next season.</p><h2>Report a result</h2><p>Complete the details below to prepare an email to HSAA. Your email app opens for you to review and send the result.</p><form class="result-form"><label>Your name<input name="name" autocomplete="name" required maxlength="120"></label><label>School<input name="school" required maxlength="160"></label><label>Competition<input name="competition" value="9-a-side — {g}" readonly></label><label>Fixture date<input type="date" name="date" required></label><label>Teams and final score<input name="score" placeholder="School A 2 – 1 School B" required maxlength="200"></label><button class="button" type="submit">Prepare results email ↗</button><p class="form-status" role="status"></p></form>'
  elif slug=='kwik-cricket':b+=f'<h2>{g.title()}’ kwik cricket</h2><p>Kwik cricket is included in HSAA’s planned 2026–27 sporting programme. Schools must be affiliated to the Young &amp; Active 2030 Programme.</p><p>For the {g}’ competition format, eligible year groups, dates and entry arrangements, please contact HSAA.</p>'
  else:b+=f'<h2>{g.title()}’ five-a-side football</h2><p>HSAA supports football opportunities for Hackney primary schools. This page is the information point for the {g}’ five-a-side competition.</p><p>Contact HSAA to find out about entry arrangements, eligible year groups, competition rules, dates and venues.</p>'
  b+='</article>'+contactbox(t.lower())+'</div>'
  (D/f'html/{key}.html').write_text(shell(key,t,desc,b,slug),encoding='utf-8')
body=intro('contact','Contact','Let’s talk school sport.','For competitions, representative teams, school participation or supporting HSAA, we’d love to hear from you.')+'''<div class="wrap content-layout"><article class="article"><span class="eyebrow">CONTACT HSAA</span><h2>Start with an email.</h2><a class="email-address" href="mailto:info@hsaa.org.uk">info@hsaa.org.uk ↗</a><p>Please include your name, school and the sport or competition you are enquiring about so we can help with your query.</p><div class="contact-topics"><section><h3>Schools &amp; competitions</h3><p>Ask about entry, affiliation, venues, dates and opportunities for your pupils.</p></section><section><h3>District teams</h3><p>Find out about boys’ and girls’ representative football and team selection.</p></section><section><h3>Support HSAA</h3><p>Get in touch if you would like to support our work or reconnect through the Hackney District Players Alumni Network.</p></section></div></article><aside class="enquiry"><span class="eyebrow">OUR COMMITMENT</span><h2>A love of sport.<br>A place for everyone.</h2><p>Our activities are underpinned by equal opportunities, child protection and safeguarding.</p><p>HSAA holds public liability insurance to support and protect children taking part in our activities and competitions.</p></aside></div>'''
(D/'html/contact.html').write_text(shell('contact','Contact','Contact HSAA at info@hsaa.org.uk for school sport and representative team enquiries.',body),encoding='utf-8')
# Hosting entrypoint: full home content, with a base for links and assets.
root=(D/'html/home.html').read_text(encoding='utf-8').replace('<head>','<head><base href="html/">',1)
(D/'index.html').write_text(root,encoding='utf-8')
print('Created 17 interlinked pages plus the root entrypoint.')
